import type { Tour } from '../types/tour.types';
import Tour1 from '../../public/img/tours/tour-1-cover.jpg';
import Tour2 from '../../public/img/tours/tour-2-cover.jpg';
import Tour3 from '../../public/img/tours/tour-3-cover.jpg';
import Tour4 from '../../public/img/tours/tour-4-cover.jpg';

export const generateMockTours = (): Tour[] => [
  {
    id: '1',
    name: 'The Forest Hiker',
    duration: 5,
    maxGroupSize: 10,
    difficulty: 'easy',
    ratingsAverage: 4.8,
    ratingsQuantity: 15,
    price: 399,
    summary: 'Breathtaking hike through the Canadian Banff National Park',
    imageCover: Tour1,
    startLocation: {
      type: 'Point',
      coordinates: [0, 0],
      description: 'Banff, CAN',
    },
    locations: [],
    startDates: ['2023-01-01'],
    slug: 'the-forest-hiker',
    images: [],
    createdAt: "2025-08-09T13:13:44.000Z",
  },
  {
    id: '2',
    name: 'The Sea Explorer',
    duration: 10,
    maxGroupSize: 10,
    difficulty: 'medium',
    ratingsAverage: 4.5,
    ratingsQuantity: 12,
    price: 999,
    summary: 'Exploring the jaw-dropping US east coast by foot and by boat',
    imageCover: Tour2,
    startLocation: {
      type: 'Point',
      coordinates: [0, 0],
      description: 'Miami, USA',
    },
    locations: [],
    startDates: ['2023-01-01'],
    slug: 'the-sea-explorer',
    images: [],
    createdAt:"2025-08-09T13:13:44.000Z",
  },
  {
    id: '3',
    name: 'The Snow Adventurer',
    duration: 5,
    maxGroupSize: 10,
    difficulty: 'difficult',
    ratingsAverage: 4.9,
    ratingsQuantity: 8,
    price: 1299,
    summary: 'Exciting adventure in the snow with snowboarding and skiing',
    imageCover: Tour3,
    startLocation: {
      type: 'Point',
      coordinates: [0, 0],
      description: 'Aspen, USA',
    },
    locations: [],
    startDates: ['2023-01-01'],
    slug: 'the-snow-adventurer',
    images: [],
    createdAt: "2025-08-09T13:13:44.000Z",
  },
    {
    id: '4',
    name: 'The City Wanderer',
    duration: 5,
    maxGroupSize: 15,
    difficulty: 'easy',
    ratingsAverage: 4.9,
    ratingsQuantity: 8,
    price: 599,
    summary: "Living the life of Wanderlust in the US' most beatiful cities",
    imageCover: Tour4,
    startLocation: {
      type: 'Point',
      coordinates: [0, 0],
      description: 'New York, USA',
    },
    locations: [],
    startDates: ['2023-01-01'],
    slug: 'the-city-wanderer',
    images: [],
    createdAt: "2025-08-09T13:13:44.000Z",
  },
];